# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envdiff < Formula
  desc "Detect environment drift before it breaks your build"
  homepage "https://github.com/bokvi/envdiff"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bokvi/envdiff/releases/download/v0.1.2/envdiff_darwin_amd64.tar.gz"
      sha256 "e6c5363b037d57bd30271fd2abb52f01252ea02506a171be4b049218f80f6dc9"

      define_method(:install) do
        bin.install "envdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bokvi/envdiff/releases/download/v0.1.2/envdiff_darwin_arm64.tar.gz"
      sha256 "55e562d0641c3938f9360aa4f0d01df86cff5a664bfc89e4efeccb72a11b23d1"

      define_method(:install) do
        bin.install "envdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bokvi/envdiff/releases/download/v0.1.2/envdiff_linux_amd64.tar.gz"
      sha256 "c32a342adeaf638d251aaa0b8bf733fa4d37dbf00305bcab00520f279973c666"
      define_method(:install) do
        bin.install "envdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bokvi/envdiff/releases/download/v0.1.2/envdiff_linux_arm64.tar.gz"
      sha256 "c40e2f5c5b6302dfd7ebd50a36dd6de786aa5c9fccb3043f3330e1610640ae8b"
      define_method(:install) do
        bin.install "envdiff"
      end
    end
  end

  test do
    system "#{bin}/envdiff", "--version"
  end
end
